# Generated by Django 6.0.7 on 2026-07-29 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testcase', '0001_initial'),
        ('testplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecuteJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PASS', 'Pass'), ('FAIL', 'Fail'), ('STOP', 'Stop')], default='PENDING', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('testplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testplan.testplan')),
            ],
        ),
        migrations.CreateModel(
            name='ExecuteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('PASS', 'Pass'), ('FAIL', 'Fail'), ('ERROR', 'Error')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('duration', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='executor.executejob')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcase.testcase')),
            ],
        ),
    ]
