# Generated by Django 6.0.7 on 2026-07-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmware_type', models.CharField(choices=[('BIOS', 'BIOS'), ('BMC', 'BMC'), ('CPLD', 'CPLD'), ('EXPANDER', 'Expander'), ('PSU', 'Power Supply')], max_length=20, verbose_name='Firmware Type')),
                ('version', models.CharField(max_length=50, verbose_name='Version')),
                ('vendor', models.CharField(blank=True, max_length=100, verbose_name='Vendor')),
                ('build_number', models.CharField(blank=True, max_length=50, verbose_name='Build Number')),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Firmware',
                'verbose_name_plural': 'Firmware',
                'ordering': ['firmware_type', '-release_date'],
            },
        ),
    ]
