# Generated by Django 6.0.7 on 2026-07-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firmware',
            options={'ordering': ['firmware_type', '-release_date']},
        ),
        migrations.AddField(
            model_name='firmware',
            name='build_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='firmware',
            name='vendor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
