# Generated by Django 6.0.7 on 2026-07-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0002_alter_firmware_options_firmware_build_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firmware',
            options={'ordering': ['firmware_type', '-release_date'], 'verbose_name': 'Firmware', 'verbose_name_plural': 'Firmware'},
        ),
        migrations.AlterField(
            model_name='firmware',
            name='build_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Build Number'),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='firmware_type',
            field=models.CharField(choices=[('BIOS', 'BIOS'), ('BMC', 'BMC'), ('CPLD', 'CPLD'), ('EXPANDER', 'Expander'), ('PSU', 'Power Supply')], max_length=20, verbose_name='Firmware Type'),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='release_date',
            field=models.DateField(verbose_name='Release Date'),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='vendor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Vendor'),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='version',
            field=models.CharField(max_length=50, verbose_name='Version'),
        ),
    ]
