# Generated by Django 6.0.7 on 2026-07-29 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_id', models.CharField(editable=False, help_text='System generated validation number', max_length=30, unique=True, verbose_name='Validation ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='Project Name')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Serial Number')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('RUNNING', 'Running'), ('PASS', 'Pass'), ('FAIL', 'Fail'), ('CANCEL', 'Cancel')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('remark', models.TextField(blank=True, verbose_name='Remark')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='Finish Time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validations', to='models_app.jbodmodel', verbose_name='JBOD Model')),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validations', to=settings.AUTH_USER_MODEL, verbose_name='Tester')),
            ],
            options={
                'verbose_name': 'Validation',
                'verbose_name_plural': 'Validations',
                'ordering': ['-created_at'],
            },
        ),
    ]
