# Generated by Django 6.0.7 on 2026-07-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('FUNCTION', 'Function'), ('HARDWARE', 'Hardware'), ('FIRMWARE', 'Firmware'), ('PERFORMANCE', 'Performance'), ('STRESS', 'Stress')], default='FUNCTION', max_length=20)),
                ('command', models.TextField(help_text='Command or script executed during the test.')),
                ('timeout', models.PositiveIntegerField(default=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
