# Generated by Django 6.0.7 on 2026-07-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=30, unique=True, verbose_name='Case ID')),
                ('name', models.CharField(max_length=100, verbose_name='Case Name')),
                ('category', models.CharField(choices=[('Function', 'Function'), ('Hardware', 'Hardware'), ('Firmware', 'Firmware'), ('Performance', 'Performance'), ('Stress', 'Stress')], max_length=30, verbose_name='Category')),
                ('command', models.TextField(verbose_name='Command / Script')),
                ('timeout', models.PositiveIntegerField(default=60, verbose_name='Timeout (Seconds)')),
                ('expected_result', models.TextField(blank=True, verbose_name='Expected Result')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Test Case',
                'verbose_name_plural': 'Test Cases',
                'ordering': ['case_id'],
            },
        ),
    ]
