# Generated by Django 6.0.7 on 2026-07-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JBODModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, unique=True, verbose_name='Model Name')),
                ('vendor', models.CharField(max_length=100, verbose_name='Vendor')),
                ('platform', models.CharField(blank=True, max_length=100, verbose_name='Platform')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'JBOD Model',
                'verbose_name_plural': 'JBOD Models',
                'ordering': ['model_name'],
            },
        ),
    ]
