# Generated by Django 6.0.7 on 2026-07-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0002_alter_firmware_options_firmware_build_number_and_more'),
        ('models_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jbodmodel',
            name='firmwares',
            field=models.ManyToManyField(blank=True, related_name='models', to='firmware.firmware'),
        ),
    ]
