# Generated by Django 6.0.7 on 2026-07-29 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firmware', '0001_initial'),
        ('models_app', '0001_initial'),
        ('testcase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firmware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firmware.firmware')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_app.jbodmodel')),
                ('testcases', models.ManyToManyField(blank=True, to='testcase.testcase')),
            ],
        ),
    ]
